apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      run: guestbook
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: guestbook
    spec:
      containers:
      - name: guestbook
        image: aa047267/web-deployment:guestbook
        ports:
        - name: http-server
          containerPort: 3000
