---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: redis-master

    spec:
      containers:
      - name: redis-master
        image: redis:2.8.23
        ports:
        - name: redis-server
          containerPort: 6379
